---
title: "Geospatial Analysis"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(sf)
library(dplyr)
library(tidyr)
library (ggplot2)
library (scales)
library (leaflet)
library (DT)
```

```{r}
## Read in shapefile using sf
ak_shp_sf <- read_sf("shapefiles/ak_regions_simp.shp")

head(ak_shp_sf)  
```
```{r}
plot(ak_shp_sf)
```


```{r}
st_crs(ak_shp_sf)
```

```{r}
ak_shp_sf <- ak_shp_sf %>% 
  st_transform(crs=3338)
plot(ak_shp_sf)
```
## spatial joins

```{r}
pop <- read.csv("shapefiles/alaska_population.csv")
```

```{r}
pop_sf <- st_as_sf(pop,
                   coords=c("lng","lat"),
                   crs=4326,
                   remove=F) %>% 
  st_transform(crs=3338)
```

```{r}
pop_joined_sf <- st_join(pop_sf, ak_shp_sf,join=st_within)
plot(pop_joined_sf["region"])
```
## group by and summarize

```{r}
pop_region <- pop_joined_sf %>% 
  as.data.frame() %>% 
  group_by(region) %>% 
  summarize(total_pop=sum(population))

head(pop_region)
```

```{r}
ak_pop_sf <- left_join(ak_shp_sf,pop_region)

plot(ak_pop_sf["total_pop"])
```

```{r}
ak_mgmt <- ak_pop_sf %>% 
  group_by(mgmt_area) %>% 
  summarise(total_pop=sum(total_pop))

plot(ak_mgmt["total_pop"])
```


```{r}
write_sf(ak_shp_sf,"shapefiles/ak_regions_population.shp")
```

# static plots

```{r}
ggplot(ak_pop_sf)+
  geom_sf(data=ak_pop_sf, aes(fill=total_pop))+
  geom_sf(data=pop_sf,size=0.5)+
  theme_bw()+
  labs(fill="Total Population")+
  scale_fill_continuous(low="khaki",high=  "firebrick", labels = comma)

```

## Interactive maps

```{r}
epsg3338 <- leaflet::leafletCRS(
  crsClass = "L.Proj.CRS",
  code = "EPSG:3338",
  proj4def =  "+proj=aea +lat_1=55 +lat_2=65 +lat_0=50 +lon_0=-154 +x_0=0 +y_0=0 +ellps=GRS80 +towgs84=0,0,0,0,0,0,0 +units=m +no_defs",
  resolutions = 2^(16:7))
```

```{r}
ak_crs <- st_transform(ak_pop_sf,crs=4326)
pop_crs <- st_transform(pop_sf,crs=4326)
```

```{r}

ak_pop_crs <- ak_pop_sf %>% st_transform(crs = 4326)
pal <- colorNumeric(palette = "Reds", domain = ak_pop_crs$total_pop)

m <- leaflet(options = leafletOptions(crs = epsg3338)) %>%
        addPolygons(data = ak_pop_crs, 
                    fillColor = ~pal(total_pop),
                    weight = 1,
                    color = "black",
                    fillOpacity = 1,
                    label = ~region) %>% 
        addLegend(position = "bottomleft",
                  pal = pal,
                  values = range(ak_pop_crs$total_pop),
                  title = "Total Population")

m
```


